AGENTS = {
    'veilleur': {
        'x': 1.26,
        'y': 103.75,
        'model': 'wamv',
        'heading': 0.0,
        'linear_velocities_limits': (0.0, 5.0),
        'angular_velocities_limits': 0.05,
        'conditions': {'drone_available': True, 'base_location': '1.260 103.750', 'drone': 'drone1', 'cible': 'cible'},
        'mission': ('reconnaissance', 'veilleur'),
    },
    'drone1': {
        'x': 1.2605,
        'y': 103.7505,
        'model': 'x500',
        'heading': 0.0,
        'linear_velocities_limits': (0.0, 8.0),
        'angular_velocities_limits': 0.05,
        'conditions': {'base_location': '1.2605 103.7505', 'cible': 'cible'},
        'mission': ('suivre_agent', 'drone1'),
    },
    'cible': {
        'x': 1.28,
        'y': 103.775,
        'model': 'wamv',
        'heading': 0.0,
        'linear_velocities_limits': (0.0, 5.0),
        'angular_velocities_limits': 0.05,
        'conditions': {},
        'mission': ('veiller', 'cible'),
    },
}
